In [2]:
import numpy as np

Suma de matrices

In [17]:
A = np.array([[1,2], [4,5]])
B = np.array([[4,3],[7,4]])
suma = A + B
print("Suma de matrices \n",suma)

Suma de matrices 
 [[ 5  5]
 [11  9]]


Multiplicación de matrices

In [11]:
mult = np.dot(A,B)
print("Producto de matrices \n", mult)

Producto de matrices 
 [[18 11]
 [51 32]]


Transposición de matriz

In [13]:
transpuesta = A.T
print("Transpuesta de A: \n", transpuesta)

Transpuesta de A: 
 [[1 4]
 [2 5]]


Determinante de una matriz

El determinante es un valor único que puede calcularse a partir de una matriz cuadrada

In [15]:
determinante = np.linalg.det(A) #det(A) = (1*5)-(2*4)
print("Determinante de A: \n", determinante)

Determinante de A: 
 -2.9999999999999996


Inversa de una matriz

In [18]:
inversa = np.linalg.inv(A)
print("Inversa de A: \n", inversa)

Inversa de A: 
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


Valores y Vectores propios

Los valores propios y los vectores propios son fundamentales en muchas aplicaciones, como en la compresión de datos y el análisis de sistemas dinámicos.

In [19]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios: \n", valores_propios)
print("Vectores propios: \n", vectores_propios)

Valores propios: 
 [-0.46410162  6.46410162]
Vectores propios: 
 [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


Sistema de ecuaciones lineales AX = BAX = BAX = B

In [20]:
B = np.array ([1,2])
X = np.linalg.solve(A,B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [-0.33333333  0.66666667]
