Arrays en numpy

In [2]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [3]:
vector = np.array([30,29,35,31,33,36,42])
print(vector)

[30 29 35 31 33 36 42]


In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [13]:
array_range = np.arange(0,10,2)
print(array_range)

[0 2 4 6 8]


In [17]:
eye_matrix = np.eye(5)
print(eye_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
diag = np.diag([1,2,3,4,5,6,7,8,9])
print(diag)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [26]:
random =np.random.random((3,5))
print(random)

[[0.13463942 0.988739   0.56454346 0.07152529 0.09713311]
 [0.65924922 0.56943468 0.69834874 0.00962268 0.82385164]
 [0.38764893 0.436918   0.61071567 0.19592326 0.30324157]]


Clase 2

In [29]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

2
(3, 3)
9
int64


In [31]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [33]:
double_array = np.array([1.3442,2,3],dtype='d')
print(double_array)

[1.3442 2.     3.    ]


In [34]:
z = z.astype(np.float64)
print(z)

3.0


In [35]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
add = np.sum(array)
print(add)

45


In [37]:
mean = np.mean(array) #Media
print(mean)

5.0


In [38]:
std = np.std(array) #Desviación estandar
print(std)

2.581988897471611
