In [1]:
import numpy as np
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [3]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices = prices + discount
print(prices)
print(discount_prices)


[[453 416 146]
 [177 326 436]
 [243 171 232]]
[[463 436 176]
 [187 346 466]
 [253 191 262]]


In [6]:
array = np.array([1,2,3,4,5])
print(np.all(array > 3))

False


In [7]:
print(np.any(array > 4))

True


In [10]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_aa = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_aa)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


In [11]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [12]:
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


In [19]:
array_sp = np.array([[1,2,3],[4,5,6],[7,8,9]])
split_array = np.split(array_sp, 3)
print(array_sp)
print(split_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
