In [3]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])
print(array[1:4])

20
50
[20 30 40]


Indexación booleana

In [5]:
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [8]:
index = [2,0,3]
print(array[index])

[30 10 40]


In [13]:
array_big = np.random.randint(1,20, size = (3,3))
print(array_big)
print(array_big[0,1])

[[ 2  7 15]
 [19 19  8]
 [14  7  1]]
7


In [16]:
print(array_big[:2,:2])

[[ 2  7]
 [19 19]]


In [18]:
array_big2 = np.random.randint(1,20, size = (20,20))
print(array_big2)
print(array_big2[5,14])

[[15  3  4 19 15 14  9 11 11  4 10  6 13 14  7  5 11  8  6  4]
 [ 3  7 13 13  1  6 14 17  9 11  4  2 15  8 15  6  8 17 18 17]
 [19 11  3  6 13  9 18 10  1 12  4  3  7  7  9 10 17  7  7  5]
 [ 8 17 16  5 17 16  2  2 16 10  3  9 16 14 10  7 10  2  4  8]
 [ 9 12 17 14  4  4  8 14  7  3  7  9  7  3  6 13 14 13  9  5]
 [12  4  7  9 19 13  2 11  7 10 16 17 19 17 15 17 13  9  1  7]
 [ 4 14  2 12  5 17 19 12 11  8 18 12  7 16  7  2  3  8 10  7]
 [16 12 19  2  7 15 15  1  3  4 13  2 12  7  4 14  3 12  8  8]
 [ 1  7 17 13 12 17 12 12 16 12  6  5 15  7 18  9 19 19 13 10]
 [13  8 13 19 18  8 10 16 16 16 17 12 18 14  7  1  5  6  3 16]
 [ 1  5 11 13 14  4 13 15 12 16  5  1 11  4  5 17 17  7  2  5]
 [ 1 17  9  7 17  2 12  2  2 16 15 16 19 18 10  9  8  9 16  7]
 [12  1 16 13  9 18 10 14 18  5 17  8  9 18 19 15  8 12  6 13]
 [ 8 19 18  7  2  9  7  7 16  6 16 11 19  3  7  2  6 17  2  4]
 [14 10 12 15 15 18  3 12  7  8 19 14 17  7  8 18 13  3  7  5]
 [ 6 18  4  2  1  9 13 10 15 18 15 15 19 14 10  8  6  1

In [19]:
print(array_big2[5:14,4:14])

[[19 13  2 11  7 10 16 17 19 17]
 [ 5 17 19 12 11  8 18 12  7 16]
 [ 7 15 15  1  3  4 13  2 12  7]
 [12 17 12 12 16 12  6  5 15  7]
 [18  8 10 16 16 16 17 12 18 14]
 [14  4 13 15 12 16  5  1 11  4]
 [17  2 12  2  2 16 15 16 19 18]
 [ 9 18 10 14 18  5 17  8  9 18]
 [ 2  9  7  7 16  6 16 11 19  3]]
